export const offersAll = [{
  city: `Amsterdam`,
  offers: [{
    id: 1010,
    coords: [52.3909553943508, 4.85309666406198],
    pictures: [`img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`],
    title: `Wood and stone place`,
    type: `room`,
    price: 999,
    isPremium: true,
    rating: 4.4,
    description: ``,
    bedrooms: 2,
    guests: 4,
    features: [],
    owner: {
      avatar: `https://api.adorable.io/avatars/128`,
      name: ``,
      isSuper: true,
    },
    reviews: [{
      id: 1110,
      avatar: `https://api.adorable.io/avatars/128`,
      name: `Angelina`,
      rating: 4.4,
      date: new Date(2020, 10, 5, 10),
      text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    }],
    offersNear: [{
      id: 1010,
      coords: [52.3909553943508, 4.85309666406198],
      pictures: [`img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`],
      title: `Wood and stone place`,
      type: `room`,
      price: 999,
      isPremium: true,
      rating: 4.4,
      description: ``,
      bedrooms: 2,
      guests: 4,
      features: [],
      owner: {
        avatar: `https://api.adorable.io/avatars/128`,
        name: ``,
        isSuper: true,
      }
    }],
  }],
}, {
  city: `Paris`,
  offers: [{
    id: 2020,
    coords: [52.3909553943508, 4.85309666406198],
    pictures: [`img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`],
    title: `Wood and stone place`,
    type: `room`,
    price: 999,
    isPremium: true,
    rating: 4.4,
    description: ``,
    bedrooms: 2,
    guests: 4,
    features: [],
    owner: {
      avatar: `https://api.adorable.io/avatars/128`,
      name: ``,
      isSuper: true,
    },
    reviews: [{
      id: 2020,
      avatar: `https://api.adorable.io/avatars/128`,
      name: `Angelina`,
      rating: 4.4,
      date: new Date(2020, 10, 5, 10),
      text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    }],
    offersNear: [{
      id: 2020,
      coords: [52.3909553943508, 4.85309666406198],
      pictures: [`img/apartment-01.jpg`, `img/apartment-02.jpg`, `img/apartment-03.jpg`, `img/room.jpg`, `img/apartment-01.jpg`, `img/apartment-02.jpg`],
      title: `Wood and stone place`,
      type: `room`,
      price: 999,
      isPremium: true,
      rating: 4.4,
      description: ``,
      bedrooms: 2,
      guests: 4,
      features: [],
      owner: {
        avatar: `https://api.adorable.io/avatars/128`,
        name: ``,
        isSuper: true,
      }
    }],
  }],
}];
